apiVersion: kubevirt.io/v1alpha1
kind: KWebUI
metadata:
  name: kubevirt-web-ui
spec:
  version: "latest"
  registry_url: "quay.io"
  registry_namespace: "kubevirt"
  branding: "okdvirt"
  imagePullPolicy: "Always"
